name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
    
jobs:
  demo_testing:
    name: test to staging
    runs-on: ubuntu-latest    

    steps:
     - name: Print Hello Message in Testing
       run : echo "Hello World from Testing job"
  
  demo_deploy:
    name: test to deploing
    runs-on: ubuntu-latest

    steps:
     - name: Print Hello Message in Deploy
       run : echo "Hello World from Deploy job"
