name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
    
jobs:
  demo_testing:
    name: test to staging
    runs-on: ubuntu-latest    

    steps:
     - name: Print Hello Message in Testing
       run : echo "Hello World from Testing job"
       
     - name: Execure few commands
       run : |
         echo "Hello Message1"
         echo "Hello Message2"
         echo "Appication name: ${{ env.APPLICATION_NAME }}"
    
     - name: List current folder
       run : ls -la
   
     - name: Git clone my repo
       uses: actions/checkout@v1   
  
     - name: List current folder
       run : ls -la
  
  demo_deploy:
    name: test to deploing
    runs-on: ubuntu-latest

    steps:
     - name: Print Hello Message in Deploy
       run : echo "Hello World from Deploy job"
